Add caching support for Satori personalizer.
heroiclabs/hiro pull request #29
Opened 2024-05-13 16:17 UTC by zyro

2024-05-13 17:25 UTC, lugehorsam commented on personalizer_satori.go
> +	cache      map[context.Context]*SatoriPersonalizerCache
Why key by context instead of user ID?

2024-05-13 17:50 UTC, lugehorsam commented
Gave feedback over DM.

2024-05-13 18:51 UTC, lugehorsam approved these changes

2024-05-14 05:00 UTC, novabyte requested changes
@zyro A small suggestion, can you make the cache refresh time a configuration option so it can be set to whatever frequency a game team would like?

It would also be good to be able to disable the behaviour entirely if desired.

2024-05-16 09:46 UTC, merged